---
- hosts: lwrchan
  user: student
  become: yes
  vars:
    seneca_id: lwrchan
    lab_dirs:
      - lab1
      - lab2
      - lab3
      - lab4
      - lab5
      - lab6
      - lab7
      - lab8

  tasks:
    - name: update apache (httpd)
      yum:
        name: httpd
        state: latest

    - name: install EPEL repository if not already
      yum:
        name: epel-release
        state: present

    - name: remove 'tree' package
      yum:
        name: tree
        state: absent

    - name: set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: create new user with Seneca ID
      user:
        name: "{{ seneca_id }}"
        groups: wheel
        append: yes
        shell: /bin/bash
        state: present
        create_home: yes

    - name: add authorized key for SSH access
      authorized_key:
        user: "{{ seneca_id }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: create lab directories
      file:
        path: "/home/{{ seneca_id }}/ops445/{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ lab_dirs }}"
